### ISSUE TITLE
OpenGL Error

### ISSUE THREAD

**Issue by tansor** [IDEA-Research/OSX#112]
Hi, @linjing7 , can you help me with the OpenGL error message? Thanks

```
python3 demo.py --gpu 0 --img_path input.png  --output_folder output_my --decoder_setting wo_decoder --pretrained_model_path ../pretrained_models/osx_l_wo_decoder.pth.tar


>>> Using GPU: 0
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
/usr/local/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
03-12 15:54:45 Load checkpoint from ../pretrained_models/osx_l_wo_decoder.pth.tar
03-12 15:54:45 Creating graph...
Load checkpoint from ../pretrained_models/osx_l_wo_decoder.pth.tar
Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2024-3-12 Python-3.9.7 torch-1.13.0+cu117 CUDA:0 (Tesla V100-SXM2-32GB, 32510MiB)

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 
Traceback (most recent call last):
  File "/root/OSX/demo/demo.py", line 96, in <module>
    vis_img = render_mesh(vis_img, mesh, smpl_x.face, {'focal': focal, 'princpt': princpt})
  File "/root/OSX/main/../common/utils/vis.py", line 143, in render_mesh
    renderer = pyrender.OffscreenRenderer(viewport_width=img.shape[1], viewport_height=img.shape[0], point_size=1.0)
  File "/usr/local/lib/python3.9/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/usr/local/lib/python3.9/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/usr/local/lib/python3.9/site-packages/pyrender/platforms/egl.py", line 186, in init_context
    self._egl_context = eglCreateContext(
  File "/usr/local/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/usr/local/lib/python3.9/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 12297,
        baseOperation = eglCreateContext,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7f040cc57740>,
                <OpenGL._opaque.EGLConfig_pointer object at 0x7f040cc576c0>,
                <OpenGL._opaque.EGLContext_pointer object at 0x7f040cc6cec0>,
                <OpenGL.arrays.lists.c_int_Array_7 object at 0x7f040cc575c0>,
        ),
        result = <OpenGL._opaque.EGLContext_pointer object at 0x7f040ccca440>
)
```

**Comment by tttran67** [comment]
To add on, when encountering the error OpenGL.error.GLError: GLError 1286, try adding renderer.delete() before the return statement in the render_mesh function in common/utils/vis.py. this worked for me.
