### ISSUE TITLE
config

### ISSUE THREAD

**Issue by tansor** [IDEA-Research/OSX#114]
Hi, @linjing7 , I've got a shape mismatch error when running demo.py and loading checkpoint. Can you help me?

```
~/OSX/demo# MESA_GL_VERSION_OVERRIDE=4.1 python3 demo.py --gpu 0 --img_path input.png --output_folder output --encoder_setting osx_l --decoder_setting normal --pretrained_model_path ../pretrained_models/osx_l.pth.tar
>>> Using GPU: 0
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
/usr/local/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
03-13 13:54:23 Load checkpoint from ../pretrained_models/osx_l.pth.tar
03-13 13:54:23 Creating graph...
Traceback (most recent call last):
  File "/root/OSX/demo/demo.py", line 45, in <module>
    demoer._make_model()
  File "/root/OSX/main/../common/base.py", line 217, in _make_model
    model.load_state_dict(new_state_dict, strict=False)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.face_decoder.neck.convs.0.conv.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 192, 1, 1]).
        size mismatch for module.face_decoder.neck.convs.1.conv.weight: copying a param with shape torch.Size([256, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 384, 1, 1]).
        size mismatch for module.face_decoder.neck.convs.2.conv.weight: copying a param with shape torch.Size([256, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 768, 1, 1]).
```

```
~/OSX/demo# ll -ah ../pretrained_models/
total 9.9G
drwxr-xr-x  3 root root 4.0K Mar 12 14:49 ./
drwxr-xr-x 13 root root 4.0K Mar 12 15:51 ../
-rw-r--r--  1 root root  225 Mar 12 14:49 README.md
-rw-r--r--  1 root root 4.8G Mar 12 14:49 osx_l.pth.tar
-rw-r--r--  1 root root 3.7G Mar 12 14:49 osx_l_wo_decoder.pth.tar
-rw-r--r--  1 root root 344M Mar 12 14:49 osx_vit_b.pth
-rw-r--r--  1 root root 1.2G Mar 12 14:49 osx_vit_l.pth
```

```
from OSX import get_model
model = get_model('test')
ckpt = torch.load('pretrained_models/osx_l.pth.tar')

In [16]: len(model.state_dict())
Out[16]: 2163

In [22]: len(ckpt['network'])
Out[22]: 2146
```

**Comment by linjing7** [comment]
Hi, it seems that other users do not meet this problem. Have you tried other settings, e.g., `--decoder_setting wo_decoder`?
