### ISSUE TITLE
run demo.py on windows  while  occur problems

### ISSUE THREAD

**Issue by flybigpig1999** [IDEA-Research/OSX#14]
D:\applications\envs\osx\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\platform\osmesa.py", line 22, in GL
    return ctypesloader.loadLibrary(
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "D:\applications\envs\osx\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: ("Could not find module 'OSMesa' (or one of its dependencies). Try using the full path with constructor syntax.", 'OSMesa', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\OSX-main\OSX-main\main\demo.py", line 15, in <module>
    from utils.vis import render_mesh, save_obj
  File "D:\Project\OSX-main\OSX-main\main\..\common\utils\vis.py", line 8, in <module>
    import pyrender
  File "D:\applications\envs\osx\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "D:\applications\envs\osx\lib\site-packages\pyrender\light.py", line 11, in <module>
    from .texture import Texture
  File "D:\applications\envs\osx\lib\site-packages\pyrender\texture.py", line 8, in <module>
    from OpenGL.GL import *
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\platform\osmesa.py", line 66, in GetCurrentContext
    function = self.OSMesa.OSMesaGetCurrentContext
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\platform\osmesa.py", line 60, in OSMesa
    def OSMesa( self ): return self.GL
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "D:\applications\envs\osx\lib\site-packages\OpenGL\platform\osmesa.py", line 28, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', "Could not find module 'OSMesa' (or one of its dependencies). Try using the full path with constructor syntax.", 'OSMesa', None)

We follow  the advice on "https://github.com/mkocabas/VIBE/issues/101",but  not work.
I don't know how to fix the issue.

**Comment by linjing7** [comment]
Hi, I do not run the code in Windows. You can try to comment out this [line](https://github.com/IDEA-Research/OSX/blob/341aae9faabb1dbb5f967c42421af6f19a523598/common/utils/vis.py#L8). It is needed only for the headless device.

**Comment by flybigpig1999** [comment]
I have tried，but it also does not work. so pity发自我的手机-------- 原始邮件 --------发件人： linjing7 ***@***.***>日期： 2023年4月12日周三 下午3:35收件人： IDEA-Research/OSX ***@***.***>抄送： flybigpig1999 ***@***.***>, Author ***@***.***>主    题： Re: [IDEA-Research/OSX] run demo.py on windows  while  occur problems (Issue #14)
Hi, I do not run the code in Windows. You can try to comment out this line. It is needed only for the headless device.

**Comment by linjing7** [comment]
You can try `sudo apt-get install libglfw3-dev libgles2-mesa-dev ` to install the libarary.

**Comment by flybigpig1999** [comment]
I also have tried, maybe the this method does not meet windows

**Comment by linjing7** [comment]
I see. I think you should refer to the install instruction from the website of `pyrender` to find out how to install `pyrender` in the `Windows` system.``

**Comment by szm0613** [comment]
I also have this problem in windows enviroment, did you solve it?

**Comment by linjing7** [comment]
@flybigpig1999 @szm0613 Hi, I have updated the code, please clone the newest code and try `pip uninstall mmpose && bash install.sh`
