### ISSUE TITLE
problem when run demo on ubuntu

### ISSUE THREAD

**Issue by HEIDIES** [IDEA-Research/OSX#26]
I have everything ready, and run "python demo.py --gpu 0 --img_path input.png --output_folder=../output", but I got the follows:

>>> Using GPU: 0
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
/home/hume/anaconda3/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
04-26 17:54:56 Load checkpoint from ../pretrained_models/osx_l.pth.tar
04-26 17:54:56 Creating graph...
Traceback (most recent call last):
  File "/home/hume/anaconda3/lib/python3.10/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/hume/anaconda3/lib/python3.10/site-packages/mmpose/models/detectors/top_down.py", line 48, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/hume/anaconda3/lib/python3.10/site-packages/mmpose/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/hume/anaconda3/lib/python3.10/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/hume/anaconda3/lib/python3.10/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/hume/anaconda3/lib/python3.10/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'ViT is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hume/PycharmProjects/OSX/demo/demo.py", line 44, in <module>
    demoer._make_model()
  File "/home/hume/PycharmProjects/OSX/main/../common/base.py", line 207, in _make_model
    model = get_model('test')
  File "/home/hume/PycharmProjects/OSX/demo/../main/OSX.py", line 418, in get_model
    vit = build_posenet(vit_cfg.model)
  File "/home/hume/anaconda3/lib/python3.10/site-packages/mmpose/models/builder.py", line 39, in build_posenet
    return POSENETS.build(cfg)
  File "/home/hume/anaconda3/lib/python3.10/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/hume/anaconda3/lib/python3.10/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/hume/anaconda3/lib/python3.10/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "TopDown: 'ViT is not in the models registry'"

**Comment by HEIDIES** [comment]
with
python: 3.10
pytorch: 2.0.0
mmcv-full: 1.7.0
mmpose: 1.0.0

**Comment by HEIDIES** [comment]
@linjing7 Hi, I tried, but the "mmpose" is not installed by default.

**Comment by HEIDIES** [comment]
OK, I will try.

**Comment by HEIDIES** [comment]
Does python 3.10 supported?

**Comment by linjing7** [comment]
I use python3.7, you can have a try.

**Comment by linjing7** [comment]
I use python3.7, you can have a try.

**Comment by HEIDIES** [comment]
If I strictly following the instruction, I should reinstall whole ubuntu with 20, and NVIDIA driver, cuda, cudnn, conda, torch :(

**Comment by linjing7** [comment]
I think you can change the cuda version. But make sure to install the mmpose by running `cd main/transformer_utils && python setup.py install`. If this can not install mmpose, you can try `python setup.py develop`.
