### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by lalisio** [IDEA-Research/OSX#44]
when "python demo --gpu 0 --img_path xxx --output_folder xxx", error turns to:

06-04 19:28:05 Load checkpoint from ../pretrained_models/osx_l.pth.tar
06-04 19:28:05 Creating graph...
Traceback (most recent call last):
  File "autodl-fs/twice/OSX/demo/demo.py", line 44, in <module>
    demoer._make_model()
  File "/root/autodl-fs/twice/OSX/demo/../common/base.py", line 209, in _make_model
    ckpt = torch.load(cfg.pretrained_model_path)
  File "/root/twice/lib/python3.8/site-packages/torch/serialization.py", line 780, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/twice/lib/python3.8/site-packages/torch/serialization.py", line 285, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

torch==1.13.1

how can we solve this o(╥﹏╥)o

**Comment by linjing7** [comment]
Hi, please install `pytorch==1.11, cuda=11.3` by `pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113`

**Comment by lalisio** [comment]
> 

ohhh，
pytorch==1.11 does work！
thanks a lot！
