### ISSUE TITLE
运行demo.py报错

### ISSUE THREAD

**Issue by Ninglily** [IDEA-Research/OSX#83]
返回结果为
>>> Using GPU: 0
/home/ljn/.local/lib/python3.8/site-packages/chumpy/__init__.py:11: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
/home/ljn/.local/lib/python3.8/site-packages/chumpy/__init__.py:11: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
/home/ljn/.local/lib/python3.8/site-packages/chumpy/__init__.py:11: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
Traceback (most recent call last):
  File "demo.py", line 42, in <module>
    from common.base import Demoer
  File "/home/ljn/OSX-main/main/../common/base.py", line 12, in <module>
    from OSX import get_model
  File "/home/ljn/OSX-main/demo/../main/OSX.py", line 4, in <module>
    from common.nets.module import PositionNet, HandRotationNet, FaceRegressor, BoxNet, BoxSizeNet, HandRoI, FaceRoI, BodyRotationNet
  File "/home/ljn/OSX-main/main/../common/nets/module.py", line 6, in <module>
    from common.utils.human_models import smpl_x
  File "/home/ljn/OSX-main/main/../common/utils/human_models.py", line 176, in <module>
    smpl = SMPL()
  File "/home/ljn/OSX-main/main/../common/utils/human_models.py", line 156, in __init__
    self.layer = {'neutral': smplx.create(cfg.human_model_path, 'smpl', gender='NEUTRAL', **self.layer_arg), 'male': smplx.create(cfg.human_model_path, 'smpl', gender='MALE', **self.layer_arg), 'female': smplx.create(cfg.human_model_path, 'smpl', gender='FEMALE', **self.layer_arg)}
  File "/home/ljn/OSX-main/main/../common/utils/smplx/smplx/body_models.py", line 2320, in create
    return SMPL(model_path, **kwargs)
  File "/home/ljn/OSX-main/main/../common/utils/smplx/smplx/body_models.py", line 134, in __init__
    data_struct = Struct(**pickle.load(smpl_file,
  File "/home/ljn/.local/lib/python3.8/site-packages/chumpy/__init__.py", line 11, in <module>
    from numpy import bool, int, float, complex, object, unicode, str, nan, inf
ImportError: cannot import name 'bool' from 'numpy' (/home/ljn/.local/lib/python3.8/site-packages/numpy/__init__.py)

**Comment by linjing7** [comment]
Hi, please refer to this [issue](https://github.com/NVIDIA/TensorRT/issues/2567).

**Comment by Ninglily** [comment]
Thank you. The problem has been resolved.
