### ISSUE TITLE
the install of mmpose

### ISSUE THREAD

**Issue by tvshow5727** [IDEA-Research/OSX#99]
>>> import mmpose
>>> mmpose.__version__
'1.3.0'

but when i show mmpose it appears :
pip3 show mmpose 
WARNING: Package(s) not found: mmpose

commomd : mim download mmpose --config td-hm_hrnet-w48_8xb32-210e_coco-256x192  --dest .
the error is ：
Traceback (most recent call last):
  File "/home/zff/.local/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/zff/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/zff/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/zff/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zff/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zff/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/zff/.local/lib/python3.8/site-packages/mim/commands/download.py", line 70, in cli
    download(package, configs, dest_root, check_certificate, dataset)
  File "/home/zff/.local/lib/python3.8/site-packages/mim/commands/download.py", line 107, in download
    return _download_configs(package, configs, dest_root,
  File "/home/zff/.local/lib/python3.8/site-packages/mim/commands/download.py", line 127, in _download_configs
    raise RuntimeError(
RuntimeError: mmpose is not installed. Please install it first.

so if the version of mmpose ==1.0.0 or mmpose==1.3.0 is ok？？

**Comment by linjing7** [comment]
Hi, please refer to the following instruction:
```
pip install openmim
mim install mmcv-full==1.7.1
cd main/transformer_utils && python setup.py install
```
